### ISSUE TITLE
Demo not working.

### ISSUE THREAD

**Issue by MichMich** [wendaosanshou/vue-fullpage#1]
You're demo doesn't seem to work. It's only showing one page.

**Comment by alisazou** [comment]
不能横向滚动

**Comment by awesomeric** [comment]
老铁，这个demo能不能修复一下，不能滚动，其他ok的 @wendaosanshou

**Comment by kodekrendel** [comment]
Lol. Demo is not working. Everybody speak Chinese. I feels like I just bought a replica iPhone from Alibaba for 1$. What a waste))

**Comment by igulyaev** [comment]
@wendaosanshou please, fix the demo

**Comment by NIeeeeee** [comment]
老铁 扎心啦 快更新一下demo～～～

**Comment by teamgroove** [comment]
@kodekrendel: the demo works just fine. If you would have taken the 2 minutes it took to place this absolutely misplaced untechnical comment about a language you do not understand, you would have clearly been able to see that the only events that trigger right now are: 'touchstart' and 'touchend'. 

If something doesn't fit into your expectations you label it 'broken' quite too fast.

The minimum thing to do now would be to add the missing code that you'd have expected and create a PR. In chinese isn't really necessary, but would be a nice step from your side in this situation.

Edit: For the records and completeness the link to the src: https://github.com/wendaosanshou/vue-fullpage/blob/master/demo/vue-fullpage-demo/src/assets/lib/index.js

### touchstart
https://github.com/wendaosanshou/vue-fullpage/blob/master/demo/vue-fullpage-demo/src/assets/lib/index.js#L122

### touchend
https://github.com/wendaosanshou/vue-fullpage/blob/master/demo/vue-fullpage-demo/src/assets/lib/index.js#L129

**Comment by taomas** [comment]
i'm sorry about that,  because of some thing i don't fix the library bug. 
i'll fix bug and update recently.

**Comment by taomas** [comment]
These bugs have been fixed
