### ISSUE TITLE
动态显示页面

### ISSUE THREAD

**Issue by FreeDeveloper-Ai** [wendaosanshou/vue-fullpage#10]
根据后台返回的结果判断页面是否显示,现在这样会出现问题

**Comment by taomas** [comment]
如果是判断某一个页面是否显示的话，可以使用```v-if```来对页面显不显示做判断。

**Comment by FreeDeveloper-Ai** [comment]
结合vue-fullpage就会出现问题,要么是空白页,要么是滑不动

**Comment by taomas** [comment]
感谢反馈，该bug现已修复，麻烦执行一下``npm install vue-fullpage --save``将vue-fullpage更新到2.0.3版本后重试一下。

**Comment by FreeDeveloper-Ai** [comment]
已经解决,谢谢!     能否说一下,是什么原因导致的呢?

**Comment by taomas** [comment]
是因为vue-fullpage的内部代码在页面状态更新的时候没有重新初始化，导致了获取当前页数的index和总页数的时候出现了失误。
现在在组件更新的时候执行了一次初始化vue-fullpage的状态就ok了。
具体代码：
https://github.com/wendaosanshou/vue-fullpage/blob/master/index.js#L23
