### ISSUE TITLE
安卓版的微信浏览器里下拉会露底(显示网页由url:abc提供)

### ISSUE THREAD

**Issue by chas125** [wendaosanshou/vue-fullpage#15]
需要对touch事件调用preventDefault方法,阻止微信浏览器的后续操作.

**Comment by mrxiaojie** [comment]
今天我们项目中也发现这个问题了，而且如果直接 touchstart 事件中preventDefault 微信的下拉，会导致后面vue 中的 点击事件失效，希望 能处理一下，谢谢

**Comment by taomas** [comment]
bug已经修复了，麻烦安装最新版本``vue-fullpage``之后，在options里面配置``preventWechat: true``

**Comment by mrxiaojie** [comment]
问题完美解决，感谢作者！
