### ISSUE TITLE
添加点击事件

### ISSUE THREAD

**Issue by Xiaoli0229** [wendaosanshou/vue-fullpage#2]
怎样在fullpage内部给元素添加点击事件 
<div class="page">
<div class="button" @click="appdownload">立刻下载</div>
</div>
这样不执行

**Comment by taomas** [comment]
抱歉这个插件因为是自己练手写的，并未怎么维护和测试，请尽量别在线上项目中使用。

最近因为比较忙也没有上github上提交过代码了，我会尽快更新该插件的，争取多测试一段时间后再更新该插件。

如果需要使用fullpage的类似功能，请参考：
[zepto.fullpage](https://github.com/yanhaijing/zepto.fullpage)
