### ISSUE TITLE
切换页面的动画效果在ios设备上不起作用

### ISSUE THREAD

**Issue by longfeiling** [wendaosanshou/vue-fullpage#7]

**Comment by taomas** [comment]
感谢反馈，该bug现已修复，麻烦通过``npm install vue-fullpage --save``最新版本再次尝试。
或者你也可以在safari浏览器访问[https://jsfiddle.net/wendaosanshou/4b6p5ujt/11/](https://jsfiddle.net/wendaosanshou/4b6p5ujt/11/)来查看线上效果。
