### ISSUE TITLE
用webpack打包的时候vue-fullpageindex.js打包出错

### ISSUE THREAD

**Issue by longfeiling** [wendaosanshou/vue-fullpage#8]
![image](https://user-images.githubusercontent.com/11283740/27213959-710acf1e-529c-11e7-8e7f-3c0ebb38d70a.png)

**Comment by taomas** [comment]
这个bug已修复，麻烦执行``npm install vue-fullpage --save``重新安装最新版本后重试一下打包。

**Comment by taomas** [comment]
如有其它问题欢迎及时反馈，谢谢。

**Comment by longfeiling** [comment]
我刚刚试了一下，还是不行呢

**Comment by longfeiling** [comment]
![image](https://user-images.githubusercontent.com/11283740/27216354-fcdf4bd6-52a7-11e7-82f6-e5c83b670818.png)

**Comment by taomas** [comment]
是安装的2.0.2版本吗？可以看一下package.json文件里面vue-fullpage的版本。
如果不是2.0.2版本，尝试一下``npm install vue-fullpage@2.0.2 --save``
有可能是使用淘宝镜像之类的原因npm的包未同步

**Comment by taomas** [comment]
如果npm是最新版本，项目目录下会有一个``package-lock.json``文件，麻烦删除这个文件后重新``npm install``，否则项目运行会有一些依赖报错。
如果需要使用淘宝镜像，建议安装nrm，nrm用来管理镜像路径挺方便的。通过``nrm ls``就能看到当前npm的镜像路径，``nrm use taobao``就能够使用淘宝镜像。
